create table recensione
(
    id              int auto_increment
        primary key,
    titolo          varchar(255)           not null,
    descrizione     text                   null,
    voto            decimal(3, 1)          not null,
    id_film         int                    null,
    id_serie        int                    null,
    id_utente       int                    not null,
    data_recensione date default curdate() null,
    constraint fk_recensione_film
        foreign key (id_film) references film (id)
            on update cascade,
    constraint fk_recensione_serie
        foreign key (id_serie) references serie (id)
            on update cascade,
    constraint fk_recensione_utente
        foreign key (id_utente) references utenti (id)
            on update cascade on delete cascade,
    check (`voto` >= 1 and `voto` <= 10)
);

INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (1, 'Ottimo film', 'Mi è piaciuto molto questo film. La trama è avvincente e gli attori sono fantastici.', 9.0, 1, null, 1, '2022-12-27');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (2, 'Deludente', 'Mi aspettavo di più da questo film. La storia è poco originale e gli effetti speciali sono mediocri.', 5.0, 1, null, 2, '2022-07-26');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (3, 'Da non perdere', 'Questa serie è semplicemente fantastica. Ogni episodio tiene incollato allo schermo.', 9.0, null, 1, 3, '2023-04-26');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (4, 'Un capolavoro', 'Ho amato ogni singola stagione di questa serie. È un mix perfetto di azione, suspense e intrighi.', 9.0, null, 1, 4, '2023-05-08');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (5, 'Consigliato', 'Un film commovente e ben interpretato. Ha saputo catturare le emozioni dello spettatore.', 8.0, 2, null, 2, '2023-04-04');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (6, 'Non all\'altezza delle aspettative', 'Mi aspettavo di più da questa serie. La trama è un po\' scontata e i personaggi poco sviluppati.', 6.0, null, 2, 3, '2022-09-10');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (7, 'Un capolavoro', 'La migliore serie che abbia mai visto. Non vedo l\'ora di scoprire cosa succederà nella prossima stagione.', 9.0, null, 2, 1, '2023-02-23');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (9, 'Suspense al massimo', 'Questa serie mi ha tenuto col fiato sospeso fino all\'ultima puntata. Consigliatissima!', 9.0, null, 3, 1, '2023-02-10');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (10, 'Superbo', 'Un film che ti cattura fin dal primo minuto. Grandi interpretazioni e una storia coinvolgente.', 9.0, 4, null, 2, '2022-07-28');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (11, 'Da rivedere', 'Una delle migliori serie di sempre. Ha saputo trattare tematiche complesse in modo brillante.', 9.0, null, 4, 1, '2022-12-27');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (12, 'Non mi è piaciuto', 'Questo film non è riuscito a coinvolgermi. La trama è confusa e gli attori poco convincenti.', 4.0, 5, null, 2, '2022-09-05');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (13, 'Serie eccezionale', 'Ho apprezzato molto questa serie. Personaggi ben sviluppati e una trama avvincente.', 9.0, null, 1, 2, '2022-11-18');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (14, 'Un film toccante', 'Questa pellicola mi ha emozionato profondamente. Gli attori hanno dato il massimo.', 8.0, 6, null, 4, '2022-10-31');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (15, 'Delusione totale', 'Mi aspettavo molto di più da questa serie. La storia è banale e i personaggi poco interessanti.', 5.0, null, 2, 4, '2022-12-20');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (16, 'Assolutamente da vedere', 'Una delle migliori serie degli ultimi anni. Non potrete fare a meno di innamorarvi dei personaggi.', 9.0, null, 3, 4, '2022-10-22');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (18, 'Intrigante e misteriosa', 'Questa serie mi ha catturato fin dall\'inizio. Ogni episodio ti lascia con il desiderio di scoprire di più.', 9.0, null, 4, 4, '2022-08-02');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (20, 'Una serie indimenticabile', 'Ho seguito questa serie per anni e non potrei essere più soddisfatto del suo finale.', 9.0, null, 5, 1, '2022-12-18');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (21, 'Un capolavoro che affascina e sorprende', 'Ho appena visto "Forrest Gump" e mi ha davvero colpito. È un film coinvolgente che ti terrà incollato allo schermo dall\'inizio alla fine.

La trama è piena di colpi di scena che ti terranno con il fiato sospeso. Gli attori sono incredibili, interpretano i loro personaggi in modo autentico e coinvolgente. La fotografia è stupefacente, con colori vibranti e inquadrature ben curate. La colonna sonora è emozionante e si integra perfettamente nelle scene.

Ciò che mi ha colpito di più di "Forrest Gump" è il modo in cui affronta temi universali come l\'amore e la ricerca della felicità. Mi ha fatto riflettere e mi ha emozionato.

In sintesi, se ti piacciono i film coinvolgenti e indimenticabili, ti consiglio "Forrest Gump". È un\'esperienza cinematografica da non perdere.', 10.0, 4, null, 3, '2023-07-07');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (26, 'Film molto bello, ma...', 'Film molto bello che tiene con il fiato sospeso dall\'inizio alla fine. Purtroppo si percepisce che è un film di altri tempi.
', 7.0, 1, null, 5, '2023-02-21');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (27, 'Un supereroe nuovo', 'Finalmente un nuovo supereroe. Giovane, fresco e innovativo.', 9.0, 11, null, 5, '2022-08-15');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (30, 'Film avvincente e commuovente', 'Davvero un bellissimo finale per questa storia. Emozionato!', 10.0, 14, null, 5, '2023-02-19');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (31, 'bellissimo', '', 9.0, 4, null, 1, '2023-04-13');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (32, 'Serie molto romantica', 'Come puoi non innamorarti del duca! Meravigliosa la storia d\'amore tra lui e Daphne. Per non parlare della seconda stagione. Non vedo l\' che esca la prossima stagione.', 10.0, null, 13, 7, '2023-06-14');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (33, 'Davvero interessante', 'Sono rimasto affascinato dalla bravura del regista e della scrittrice che hanno creato una storia d\'amore simile a quelle dei giorni nostri ambientandola perfettamente nella Londra del XIV secolo', 8.0, null, 13, 8, '2022-11-13');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (34, 'Un\'entusiasmante rapina che non delude', 'La casa di carta è una serie che sa come tenere il pubblico sulle spine. La trama intricata, i personaggi ben sviluppati e i colpi di scena imprevedibili rendono questa serie un\'esperienza imperdibile per gli amanti dell\'azione e della suspense.', 10.0, null, 5, 8, '2023-06-12');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (35, 'Una serie coinvolgente ma con qualche caduta di ritmo', 'La casa di carta offre un mix avvincente di azione, suspense e drammi personali. Tuttavia, in alcuni momenti la trama può perdere un po\' di slancio, rallentando il ritmo complessivo. Nonostante ciò, la serie rimane un\'esperienza coinvolgente e ben realizzata.', 8.0, null, 5, 3, '2023-01-30');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (36, 'Un\'opera di intrighi e tradimenti, ma con alcune pecche', 'La casa di carta presenta una trama intricata che ruota attorno a rapine audaci e personaggi carismatici. Tuttavia, alcune sottotrame possono risultare poco convincenti e alcuni personaggi non sviluppati a fondo. Nonostante queste pecche, la serie riesce comunque a intrattenere grazie alla sua tensione e agli intrecci narrativi.', 6.0, null, 5, 6, '2023-07-13');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (37, 'Un\'epica avventura fantasy che incanta', 'Il Signore degli Anelli: La Compagnia dell\'Anello è un capolavoro dell\'epica fantasy. La storia coinvolgente, gli scenari mozzafiato e gli effetti speciali strabilianti trasportano gli spettatori in un mondo magico e avvincente, creando un\'esperienza cinematografica indimenticabile', 9.0, 2, null, 1, '2022-11-12');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (38, 'Un inizio magistrale ma con qualche scena prolungata', 'Il film ha un inizio magistrale che introduce perfettamente il mondo di Tolkien. Tuttavia, in alcune occasioni alcune scene potrebbero risultare un po\' prolungate, rallentando leggermente il ritmo. Nonostante ciò, l\'immersione nel mondo di Tolkien e le performance degli attori rendono il film un\'esperienza epica da non perdere', 8.0, 2, null, 3, '2023-03-10');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (39, 'Un capolavoro immortale del cinema gangster', 'Il Padrino è un capolavoro immortale del cinema gangster. La regia magistrale, le interpretazioni straordinarie e la trama avvincente creano un\'esperienza cinematografica indimenticabile che ha lasciato un\'impronta indelebile nella storia del cinema.', 9.0, 3, null, 4, '2022-10-21');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (40, 'Un racconto oscuro e coinvolgente di potere e famiglia', 'Il Padrino è un racconto oscuro e coinvolgente che esplora il mondo del crimine organizzato e le dinamiche familiari complesse. La perfetta caratterizzazione dei personaggi, le intense performance attoriali e la regia di maestria contribuiscono a creare un\'opera cinematografica senza tempo.', 7.0, 3, null, 5, '2022-11-29');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (41, 'Deludente esempio di cinema gangster', 'Nonostante il riconoscimento universale, devo ammettere che Il Padrino non ha soddisfatto le mie aspettative. Ho trovato la trama confusa e lenta, senza un vero senso di progressione. Le performance degli attori sono state apprezzabili, ma nel complesso il film non mi ha coinvolto come speravo.', 6.0, 3, null, 6, '2022-08-07');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (42, 'Un esercizio di stile senza una vera sostanza', 'Personalmente, Pulp Fiction è stato un esercizio di stile senza una vera sostanza. Ho trovato la trama frammentata e il ritmo troppo lento per il mio gusto. Non ho fatto un reale collegamento con i personaggi e la violenza eccessiva ha reso il film difficile da digerire', 6.0, 5, null, 7, '2022-09-19');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (43, 'Un capolavoro audace e travolgente di Tarantino', 'Pulp Fiction è un capolavoro audace e travolgente che incarna perfettamente lo stile unico di Quentin Tarantino. La trama non lineare, i dialoghi taglienti e le performance eccezionali si combinano per creare un\'esperienza cinematografica indimenticabile che ha influenzato il cinema contemporaneo.', 9.0, 5, null, 8, '2023-03-31');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (44, 'Un capolavoro di fantascienza onirica', 'Inception è un capolavoro di fantascienza onirica che sfida la mente dello spettatore. La trama intricata, gli effetti visivi spettacolari e le interpretazioni straordinarie creano un\'esperienza coinvolgente e riflessiva. Un film che spinge i confini della realtà e che continua a stimolare la discussione e l\'interpretazione.', 9.0, 6, null, 1, '2023-07-14');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (45, 'Un\'idea interessante ma esecuzione deludente', 'Nonostante l\'interessante premessa di Inception, sono rimasto deluso dalla sua esecuzione. La trama si perde in una sovrabbondanza di concetti e il film risulta troppo lungo, rallentando il ritmo complessivo. Non sono riuscito a creare un vero legame emotivo con i personaggi e alla fine ho trovato l\'esperienza confusa e poco appagante.', 6.0, 6, null, 2, '2023-05-23');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (46, 'Un film ambizioso ma con una trama complessa', 'Inception è un film ambizioso che affronta concetti complessi come la realtà e l\'illusione. Tuttavia, la trama intricata potrebbe risultare confusa per alcuni spettatori, richiedendo una certa attenzione per seguire le varie sottotrame. Nonostante ciò, la regia magistrale e l\'innovativo concetto del film lo rendono un\'opera straordinaria nel panorama della fantascienza.', 8.0, 6, null, 3, '2022-10-22');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (47, 'Un\'epica oscura che ridefinisce i film di supereroi', 'Il cavaliere oscuro è un\'epica oscura che ridefinisce il genere dei film di supereroi. La trama complessa, le performance straordinarie, in particolare di Heath Ledger come Joker, e la regia di Christopher Nolan creano un\'atmosfera intensa e coinvolgente che si distingue nel panorama cinematografico.', 9.0, 9, null, 4, '2023-04-27');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (48, 'Un film cupo ma con alcune lunghezze', 'Il cavaliere oscuro è un film cupo e avvincente che esplora il lato oscuro della giustizia. Tuttavia, in alcuni momenti la trama potrebbe sembrare un po\' prolungata, rallentando il ritmo complessivo. Nonostante ciò, le performance straordinarie e la profondità dei temi trattati rendono il film un\'opera imprescindibile per gli amanti del genere.', 8.0, 9, null, 5, '2022-08-21');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (49, 'Un\'opera sopravvalutata che manca di sostanza', 'Sono rimasto deluso da Il cavaliere oscuro, considerato da molti un capolavoro. Ho trovato la trama confusa e i personaggi poco sviluppati. Nonostante alcune scene d\'azione ben realizzate, il film manca di sostanza e non mi ha coinvolto emotivamente.', 7.0, 9, null, 6, '2022-09-08');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (50, 'Un\'epica avventura storica di coraggio e vendetta', 'Il gladiatore è un\'epica avventura storica che cattura lo spettatore con la sua storia di coraggio e vendetta. Le emozionanti scene di combattimento, la magnifica colonna sonora e la performance memorabile di Russell Crowe creano un film che si distingue per la sua grandiosità e intensità.', 10.0, 10, null, 6, '2022-12-24');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (51, 'Un film avvincente ma con qualche cliché', 'Il gladiatore è un film avvincente che racconta una storia epica di lotta per la libertà. Tuttavia, in alcuni momenti la trama può cadere in alcuni cliché del genere, rendendo alcune parti prevedibili. Nonostante ciò, le forti interpretazioni e le sequenze di combattimento ben coreografate rendono il film una visione coinvolgente.', 8.0, 10, null, 7, '2023-04-19');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (52, 'Un\'opera sopravvalutata con una trama banale', 'Personalmente, ho trovato Il gladiatore un\'opera sopravvalutata con una trama banale. Non ho trovato il personaggio principale particolarmente interessante e ho trovato alcune sequenze di combattimento troppo lunghe e ripetitive. Nel complesso, il film non ha soddisfatto le mie aspettative.', 5.0, 10, null, 8, '2022-12-31');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (53, 'Un divertente e sorprendente film sui supereroi', 'Shazam è un divertente e sorprendente film sui supereroi che mescola azione, commedia e cuore. La storia di un ragazzino che diventa un eroe con superpoteri offre una prospettiva fresca e le performance dei giovani attori sono fantastiche. Un film che dona un sorriso e dimostra che anche i supereroi possono essere divertenti.', 9.0, 11, null, 1, '2022-07-23');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (54, 'Un film divertente ma con una trama poco profonda', 'Shazam è un film divertente che riesce a intrattenere grazie all\'umorismo e alle situazioni esilaranti. Tuttavia, la trama risulta poco profonda e prevedibile, mancando di una maggiore complessità e profondità emotiva. Nonostante ciò, le performance del cast giovane e l\'energia positiva rendono il film una visione piacevole.', 7.0, 11, null, 2, '2023-04-02');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (55, 'Un tentativo deludente di un film sui supereroi', 'Sfortunatamente, Shazam è stato un tentativo deludente di realizzare un film sui supereroi. Ho trovato l\'umorismo forzato e le gag poco divertenti. La trama era prevedibile e i personaggi non mi hanno coinvolto emotivamente. Nel complesso, il film non ha raggiunto le aspettative che avevo.', 4.0, 11, null, 3, '2023-01-13');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (56, 'Un\'avventura divertente e sorprendente', 'Jumanji: Benvenuti nella giungla è un\'avventura divertente e sorprendente che mescola azione, comicità e una buona dose di nostalgia. Il cast affiatato e le dinamiche tra i personaggi rendono il film un\'esperienza piacevole per tutta la famiglia. Un sequel che riesce a catturare lo spirito del film originale.', 8.0, 13, null, 4, '2022-11-18');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (57, 'Un rinfrescante riavvio che offre divertimento e avventura', 'Jumanji: Benvenuti nella giungla è un rinfrescante riavvio del classico film. La trama coinvolgente, le sequenze di azione emozionanti e le interpretazioni divertenti del cast portano nuova vita alla storia di Jumanji. Un film che offre divertimento e avventura per grandi e piccini.', 9.0, 13, null, 5, '2022-10-04');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (58, 'Un film divertente ma con una trama poco originale', 'Jumanji: Benvenuti nella giungla è un film divertente che riesce a far ridere grazie all\'umorismo e alle situazioni esilaranti. Tuttavia, la trama risulta poco originale, seguendo il tipico schema delle avventure nel mondo dei videogiochi. Nonostante ciò, il cast affiatato e l\'energia positiva rendono il film una visione piacevole.', 7.0, 13, null, 6, '2022-08-09');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (59, 'Un finale epico e commovente per l\'era degli Avengers', 'Avengers: Endgame è un finale epico e commovente che chiude in modo spettacolare l\'era degli Avengers. La trama coinvolgente, le emozionanti performance degli attori e le spettacolari scene d\'azione creano un\'esperienza cinematografica straordinaria che celebra il potere dei supereroi.', 10.0, 14, null, 7, '2023-03-17');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (60, 'Una conclusione grandiosa piena di sorprese', 'Avengers: Endgame offre una conclusione grandiosa per l\'universo Marvel, piena di sorprese e colpi di scena. La regia magistrale, le dinamiche tra i personaggi e il mix perfetto di azione, emozione e umorismo rendono il film un\'esperienza epica per gli appassionati dei supereroi.', 10.0, 14, null, 8, '2022-09-07');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (61, 'Un blockbuster sovraffollato e sopravvalutato', 'Personalmente, ho trovato Avengers: Endgame un blockbuster sovraffollato e sopravvalutato. Ho trovato difficile seguire tutte le sottotrame e i personaggi presenti nel film. Nonostante alcune scene d\'azione spettacolari, ho perso l\'empatia con i personaggi e ho trovato la durata eccessiva. Nel complesso, il film non ha soddisfatto le mie aspettative.', 7.0, 14, null, 1, '2023-04-02');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (65, 'Shazam: la furia degli dei', 'Shazam: la furia degli dei è un sequel che supera l\'originale in tutti i sensi. Il film è ricco di azione, humor e cuore, e offre un\'esperienza di intrattenimento senza pari. Zachary Levi è fantastico come Shazam, e il cast di supporto è altrettanto bravo. Le scene d\'azione sono spettacolari, e i dialoghi sono divertenti e intelligenti. Shazam: la furia degli dei è un film che piacerà a tutti, dai fan dei supereroi ai semplici amanti del cinema.', 10.0, 12, null, 1, '2022-08-29');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (66, 'Shazam: la furia degli dei', 'Shazam: la furia degli dei è un film divertente e pieno di sorprese. Il film è ricco di azione, humor e cuore, e offre un \'esperienza di intrattenimento senza pari. Zachary Levi è fantastico come Shazam, e il cast di supporto è altrettanto bravo. Le scene d\'azione sono spettacolari, e i dialoghi sono divertenti e intelligenti. Shazam: la furia degli dei è un film che piacerà a tutti, dai fan dei supereroi ai semplici amanti del cinema.', 9.0, 12, null, 4, '2023-01-02');
INSERT INTO moviemania.recensione (id, titolo, descrizione, voto, id_film, id_serie, id_utente, data_recensione) VALUES (67, 'Shazam: la furia degli dei', 'Shazam: la furia degli dei è un sequel deludente. Il film è ricco di azione, ma manca di humor e cuore. Zachary Levi è ancora bravo come Shazam, ma il cast di supporto è meno ispirato. Le scene d\'azione sono spettacolari, ma i dialoghi sono banali e prevedibili. Shazam: la furia degli dei è un film che piacerà solo ai fan più accaniti del personaggio.', 6.0, 12, null, 8, '2023-06-30');
